# **Python syntax**

In [ ]:
a = 10
print("Hello World") # string
print(float(a)) #float
print(a) # int
print(a > 10) # bool

Hello World
10.0
10
False


In [ ]:
# f-string print & variable & input
a = 10
b = int(input())
print(f"The sum of A+B is {a+b}") # f-string print

20
The sum of A+B is 30


In [ ]:
# for loop
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
# for loop with array
fruits = ["apple", "banana", "orange", "grape", "coconut", "papaya", "durian", "mango", "pineapple"]
for fruit in fruits:
  print(fruit)

apple
banana
orange
grape
coconut
papaya
durian
mango
pineapple


In [ ]:
# if-else
fruits = ["apple", "banana", "orange", "grape", "coconut", "papaya", "durian", "mango", "pineapple"]
if "apple" in fruits: #True
  print("yes")
else: print("No")

yes


In [ ]:
# Data type + isinstance
a = 10
print(isinstance(a, str))
print(type(a))

False
<class 'int'>


In [ ]:
# Array & Tuple
fruits = ["apple", 3, "orange", 4, "coconut", 5, "durian", 6, "pineapple"]

print(fruits[0])
print(fruits[-1])
print(fruits[0:-1]) # Slicing
print('')

for fruit in fruits:
  if isinstance(fruit, str):
    print(fruit)
  else:
    continue

apple
pineapple
['apple', 3, 'orange', 4, 'coconut', 5, 'durian', 6]

apple
orange
coconut
durian
pineapple


In [ ]:
# Dictionaries
d = {1: 'Geeks', 2: 'For', 3: 'Geeks', 'age':22}

# Using del to remove an item
del d["age"]
print(d)

# Using pop() to remove an item and return the value
val = d.pop(1)
print(val)

# Using popitem to removes and returns
# the last key-value pair.
key, val = d.popitem()
print(f"Key: {key}, Value: {val}")

# Clear all items from the dictionary
d.clear()
print(d)

c^2 = a^2 + b^2

In [ ]:
# Function
def pythagorus(a,b):
  return (a**2 + b**2) ** (1/2)
print(pythagorus(3, 4))

5.0


In [ ]:
# Lambda function
pythagorus = lambda a, b: (a**2 + b**2) ** (1/2)
print(pythagorus(3, 4))

5.0


# **Numpy**

In [ ]:
import numpy as np

a = np.array([7,2,9,10])

In [ ]:
print(a)

[ 7  2  9 10]


In [ ]:
print(a.dtype)

int64


In [ ]:
b = np.array([1,2,3,4.5])

print(b.dtype)

float64


A frequent error consists in calling array with multiple arguments, rather than providing a single sequence as an argument.

np.array(**sequence of numbers**)

In [ ]:
a = np.array(1,2,3,4)    # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [ ]:
a = np.array([1,2,3,4])  # RIGHT

In [ ]:
print(a)

[1 2 3 4]


array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [ ]:
# 1st sequence -> [1,2,3,5]
# 2nd sequence -> [4,5,6,7]
# 3rd sequence -> [4,5,2,1]

b = np.array([[1,2,3,5], [4,5,6,7], [4,5,2,1]])

print(b)

[[1 2 3 5]
 [4 5 6 7]
 [4 5 2 1]]


In [ ]:
b.shape

(3, 4)

In [ ]:
# 1st sequence of sequences -> [[1,2,3,5], [4,5,6,7], [4,5,2,1]]
# 2nd sequence of sequences -> [[3,4,6,8], [7,8,9,10], [3,5,7,10]]

c = np.array([[[1,2,3,5], [4,5,6,7], [4,5,2,1]],
             [[3,4,6,8], [7,8,9,10], [3,5,7,10]]])

print(c)

In [ ]:
c.shape

In [ ]:
d = np.zeros((3, 4)) # create zeros matrix with (3,4) shape.

print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
e = np.ones((2,3), dtype=int) # create ones matrix with (2,3) shape.

print(e)

[[1 1 1]
 [1 1 1]]


In [ ]:
f = np.ones((2,3), dtype=float) # create ones matrix with (2,3) shape.

print(f)


In [ ]:
g = np.random.random((3,3)) # create random matrix with (3, 3) shape.

print(g)

[[0.49269542 0.56179812 0.27603617]
 [0.05353912 0.80617739 0.68959992]
 [0.64632691 0.87251998 0.13608088]]


## Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [ ]:
a = np.array([2, 40, 73, 87])

b = np.array([1, 20, 20, 50])

c = a - b

print(c)

[ 1 20 53 37]


In [ ]:
d = a ** 2

print(d)

[   4 1600 5329 7569]


In [ ]:
e = np.array([0, np.pi, 2*np.pi])

f = np.cos(e)

print(f)

[ 1. -1.  1.]


In [ ]:
g = np.array([10, 20 ,30 ,40])

h = g < 30

print(h)

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:



In [ ]:
A = np.array([[1, 1], [0, 1]])

B = np.array([[2, 0], [3, 4]])

elementwise_product = A*B # elementwise product

print(elementwise_product)

[[2 0]
 [0 4]]


Let's try this!

http://matrixmultiplication.xyz/

In [ ]:
matrix_product = A@B # matrix product

print(matrix_product)


[[5 4]
 [3 4]]


In [ ]:
another_matrix_product = A.dot(B) # another matrix product

print(another_matrix_product)

In [ ]:
matrix = np.array([[[1,2,3,5], [4,5,6,7], [4,5,2,1]],
             [[3,4,6,8], [7,8,9,10], [3,5,7,10]]])

print(matrix)

print(matrix.sum())

print(matrix.min())

print(matrix.max())


[[[ 1  2  3  5]
  [ 4  5  6  7]
  [ 4  5  2  1]]

 [[ 3  4  6  8]
  [ 7  8  9 10]
  [ 3  5  7 10]]]
125
1
10


In [ ]:
a = np.arange(0, 4, 0.5)

print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [ ]:
b = np.arange( 0.0, 3.5, 0.3 ) # create matrix that has values from 0.0 to 2.1 increasing by 0.3 each

print(b)

print(b.shape)

[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3.  3.3]
(12,)


In [ ]:
c = b.reshape(3,4)

print(c)

[[0.  0.3 0.6 0.9]
 [1.2 1.5 1.8 2.1]
 [2.4 2.7 3.  3.3]]


In [ ]:
print(c.sum(axis=0)) #sum of each coloumn

[3.6 4.5 5.4 6.3]


In [ ]:
print(c.min(axis=1)) #min of each row

[0.  1.2 2.4]


In [ ]:
d = np.exp(c) #apply exponential function to the matrix

print(d)

[[ 1.          1.34985881  1.8221188   2.45960311]
 [ 3.32011692  4.48168907  6.04964746  8.16616991]
 [11.02317638 14.87973172 20.08553692 27.11263892]]


In [ ]:
e = np.sqrt(c) #apply square root function to the matrix

print(e)

[[0.         0.54772256 0.77459667 0.9486833 ]
 [1.09544512 1.22474487 1.34164079 1.44913767]
 [1.54919334 1.64316767 1.73205081 1.81659021]]


## Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [ ]:
a = np.arange(10)**3

print(a)

In [ ]:
a[2]

In [ ]:
a[2:5]

In [ ]:
a[ : :-1]

Multi dimentional array.

In [ ]:
A = np.array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

print(A)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [ ]:
A[2,3]

np.int64(23)

In [ ]:
A[0:5, 1] # each row in the second column of A

array([ 1, 11, 21, 31, 41])

In [ ]:
A[ : ,1] # equivalent to the previous example

In [ ]:
A[1:3, : ] # each column in the second and third row of b

In [ ]:
A[-1] # the last row. Equivalent to A[-1,:]

## Linear Algebra

Work in progress. Basic linear algebra to be included here.

### Simple Array Operations
See linalg.py in numpy folder for more.

In [ ]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])

print(a)

[[1. 2.]
 [3. 4.]]


In [ ]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [ ]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# **Pandas**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Create DataFrame
data = {'name': ['John', 'Jo', 'Joe'],
        'age': [20, 25, 30],
        'absent': [False, False, True]}
df = pd.DataFrame(data)

In [ ]:
df

name  age  absent
0  John   20   False
1    Jo   25   False
2   Joe   30    True

In [ ]:
df['status'] = np.nan

In [ ]:
df

name  age  absent  status
0  John   20   False     NaN
1    Jo   25   False     NaN
2   Joe   30    True     NaN

In [ ]:
df['status'] = df['status'].fillna("Human")

In [ ]:
df

name  age  absent status
0  John   20   False  Human
1    Jo   25   False  Human
2   Joe   30    True  Human

In [ ]:
df.isna().sum()

name      0
age       0
absent    0
status    0
dtype: int64

## **working with csv file**

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [ ]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [ ]:
df.head(100)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0     -114.31     34.19                15.0       5612.0          1283.0   
1     -114.47     34.40                19.0       7650.0          1901.0   
2     -114.56     33.69                17.0        720.0           174.0   
3     -114.57     33.64                14.0       1501.0           337.0   
4     -114.57     33.57                20.0       1454.0           326.0   
..        ...       ...                 ...          ...             ...   
95    -115.58     32.81                 5.0        805.0           143.0   
96    -115.58     32.81                10.0       1088.0           203.0   
97    -115.58     32.79                14.0       1687.0           507.0   
98    -115.58     32.78                 5.0       2494.0           414.0   
99    -115.59     32.85                20.0       1608.0           274.0   

    population  households  median_income  median_house_value  
0       1015.0       472.0         1.4936             66900.0  
1       1129.0       463.0         1.8200             80100.0  
2        333.0       117.0         1.6509             85700.0  
3        515.0       226.0         3.1917             73400.0  
4        624.0       262.0         1.9250             65500.0  
..         ...         ...            ...                 ...  
95       458.0       143.0         4.4750             96300.0  
96       533.0       201.0         3.6597             87500.0  
97       762.0       451.0         1.6635             64400.0  
98      1416.0       421.0         5.7843            110100.0  
99       862.0       248.0         4.8750             90800.0  

[100 rows x 9 columns]

In [ ]:
df.tail()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


In [ ]:
df.iloc[0, 1]

np.float64(34.19)

In [ ]:
df.loc[0, 'median_house_value']

np.float64(66900.0)

In [ ]:
df.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       total_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [ ]:
df.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

## **working with json**

In [ ]:
df_json = pd.read_json('/content/sample_data/anscombe.json')

In [ ]:
df_json

Series   X      Y
0       I  10   8.04
1       I   8   6.95
2       I  13   7.58
3       I   9   8.81
4       I  11   8.33
5       I  14   9.96
6       I   6   7.24
7       I   4   4.26
8       I  12  10.84
9       I   7   4.81
10      I   5   5.68
11     II  10   9.14
12     II   8   8.14
13     II  13   8.74
14     II   9   8.77
15     II  11   9.26
16     II  14   8.10
17     II   6   6.13
18     II   4   3.10
19     II  12   9.13
20     II   7   7.26
21     II   5   4.74
22    III  10   7.46
23    III   8   6.77
24    III  13  12.74
25    III   9   7.11
26    III  11   7.81
27    III  14   8.84
28    III   6   6.08
29    III   4   5.39
30    III  12   8.15
31    III   7   6.42
32    III   5   5.73
33     IV   8   6.58
34     IV   8   5.76
35     IV   8   7.71
36     IV   8   8.84
37     IV   8   8.47
38     IV   8   7.04
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89

In [ ]:
df_json['Series'].value_counts()

Series
I      11
II     11
III    11
IV     11
Name: count, dtype: int64